In [300]:
StudyAnalysis

calcmain.models.StudyAnalysis

In [4]:
from django.shortcuts import render, redirect, get_object_or_404
study = get_object_or_404(StudyAnalysis, pk=1)
import pandas as pd

processed_df = study.processed_df
processed_df

,Patient ID,Number of solid tumor,Number of lymph node,sum_base,sum_post,Lesion size at the baseline (mm),Percent change (%)
0,1,2,1,140,255,NaN,82
1,2,1,2,144,154,NaN,6
2,3,1,2,148,92,NaN,-38
3,4,3,2,332,469,NaN,41
4,5,2,1,161,221,NaN,37
5,6,3,2,388,130,NaN,-67
6,7,2,1,233,165,NaN,-30
7,8,0,2,138,89,NaN,-36
8,9,2,0,62,206,NaN,232
9,10,3,1,373,239,NaN,-36
10,11,1,2,188,159,NaN,-16
11,12,1,2,139,102,NaN,-27
12,13,2,2,264,108,NaN,-60
13,14,1,2,218,179,NaN,-18
14,15,3,1,278,306,NaN,10
15,16,1,2,126,120,NaN,-5
16,17,1,2,254,164,NaN,-36
17,18,2,2,233,209,NaN,-11
18,19,1,2,191,204,NaN,6
19,20,2,1,317,258,NaN,-19
20,21,1,2,237,151,NaN,-37
21,22,2,2,103,132,NaN,28
22,23,2,2,375,142,NaN,-63
23,24,2,2,256,142,NaN,-45
24,25,4,1,307,480,NaN,56
25,26,1,2,90,126,NaN,40
26,27,2,2,224,315,NaN,40
27,28,2,2,311,259,NaN,-17
28,29,0,1,45,83,45.0,84
29,30,1,2,199,84,NaN,-58

In [3]:
study.study_name

'Test1'

In [8]:
processed_df = study.processed_df
processed_df

,Patient ID,Number of solid tumor,Number of lymph node,sum_base,sum_post,Lesion size at the baseline (mm),Percent change (%)
0,1,2,1,140,255,NaN,82
1,2,1,2,144,154,NaN,6
2,3,1,2,148,92,NaN,-38
3,4,3,2,332,469,NaN,41
4,5,2,1,161,221,NaN,37
5,6,3,2,388,130,NaN,-67
6,7,2,1,233,165,NaN,-30
7,8,0,2,138,89,NaN,-36
8,9,2,0,62,206,NaN,232
9,10,3,1,373,239,NaN,-36
10,11,1,2,188,159,NaN,-16
11,12,1,2,139,102,NaN,-27
12,13,2,2,264,108,NaN,-60
13,14,1,2,218,179,NaN,-18
14,15,3,1,278,306,NaN,10
15,16,1,2,126,120,NaN,-5
16,17,1,2,254,164,NaN,-36
17,18,2,2,233,209,NaN,-11
18,19,1,2,191,204,NaN,6
19,20,2,1,317,258,NaN,-19
20,21,1,2,237,151,NaN,-37
21,22,2,2,103,132,NaN,28
22,23,2,2,375,142,NaN,-63
23,24,2,2,256,142,NaN,-45
24,25,4,1,307,480,NaN,56
25,26,1,2,90,126,NaN,40
26,27,2,2,224,315,NaN,40
27,28,2,2,311,259,NaN,-17
28,29,0,1,45,83,45.0,84
29,30,1,2,199,84,NaN,-58

In [7]:
len(processed_df.index)

30

In [15]:
processed_df.loc[:, "Percent change (%)"][29]

-58

In [103]:
processed_df = study.processed_df
up_patients = study.up_patients
num_all_patients = len(processed_df.index) + up_patients
print(num_all_patients)

50

In [31]:
num_partial_response = num_progression = 0

for id in range(len(processed_df.index)):
    if processed_df.loc[:, "Percent change (%)"][id] < -30:
        num_partial_response += 1
    elif processed_df.loc[:, "Percent change (%)"][id] >= 20:
        num_progression += 1
        
# 10 9

partial_response_prop = round(num_partial_response / num_all_patients * 100, 2)
progression_prop = round((num_progression + up_patients) / num_all_patients * 100, 2)

print(partial_response_prop, progression_prop)

20.0 58.0

In [34]:
sorted(processed_df.loc[:, "Percent change (%)"], reverse=True)

[232,
 84,
 82,
 56,
 41,
 40,
 40,
 37,
 28,
 10,
 6,
 6,
 -5,
 -11,
 -16,
 -17,
 -18,
 -19,
 -27,
 -30,
 -36,
 -36,
 -36,
 -37,
 -38,
 -45,
 -58,
 -60,
 -63,
 -67]

In [37]:
x = [i for i in range(len(processed_df.index))]
x

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29]

In [65]:
processed_df["Percent change (%)"].values.flatten()

# column은 알파벳순으로 자동정렬
data={'state':['Ohio','Ohio','Ohio','Nevada','Nevada'],
     'year':[2000,2001,2002,2001,2002],
     'pop':[1.5,1.7,3.6,2.4,2.9]}
df=DataFrame(data)
df

array([ 82,   6, -38,  41,  37, -67, -30, -36, 232, -36, -16, -27, -60,
       -18,  10,  -5, -36, -11,   6, -19, -37,  28, -63, -45,  56,  40,
        40, -17,  84, -58], dtype=int64)

In [69]:
sorted(processed_df.loc[:, "Percent change (%)"], reverse=True)

[232,
 84,
 82,
 56,
 41,
 40,
 40,
 37,
 28,
 10,
 6,
 6,
 -5,
 -11,
 -16,
 -17,
 -18,
 -19,
 -27,
 -30,
 -36,
 -36,
 -36,
 -37,
 -38,
 -45,
 -58,
 -60,
 -63,
 -67]

In [80]:
new_data = {'Index': [i+1 for i in range(len(processed_df.index))],
           'Percent change (%)': sorted(processed_df.loc[:, "Percent change (%)"], reverse=True)}
change_df = pd.DataFrame(new_data)
change_df.loc[-1] = ['Index','Percent change (%)']  
change_df.index = change_df.index + 1  
change_df = change_df.sort_index()
change_df
change_df.values.tolist()

[['Index', 'Percent change (%)'],
 [1, 232],
 [2, 84],
 [3, 82],
 [4, 56],
 [5, 41],
 [6, 40],
 [7, 40],
 [8, 37],
 [9, 28],
 [10, 10],
 [11, 6],
 [12, 6],
 [13, -5],
 [14, -11],
 [15, -16],
 [16, -17],
 [17, -18],
 [18, -19],
 [19, -27],
 [20, -30],
 [21, -36],
 [22, -36],
 [23, -36],
 [24, -37],
 [25, -38],
 [26, -45],
 [27, -58],
 [28, -60],
 [29, -63],
 [30, -67]]

In [59]:
change_df.values.tolist()

[[9, 232],
 [29, 84],
 [1, 82],
 [25, 56],
 [4, 41],
 [27, 40],
 [26, 40],
 [5, 37],
 [22, 28],
 [15, 10],
 [19, 6],
 [2, 6],
 [16, -5],
 [18, -11],
 [11, -16],
 [28, -17],
 [14, -18],
 [20, -19],
 [12, -27],
 [7, -30],
 [8, -36],
 [10, -36],
 [17, -36],
 [21, -37],
 [3, -38],
 [24, -45],
 [30, -58],
 [13, -60],
 [23, -63],
 [6, -67]]

In [109]:
# processed_df = processed_df.sort_values(by='Percent change (%)', ascending=False)
# processed_df

new_data = {'Index': [i+1 for i in range(len(processed_df.index))],
           'Percent change (%)': sorted(processed_df.loc[:, "Percent change (%)"], reverse=True)}
sorted_df = pd.DataFrame(new_data)
sorted_df

    Index  Percent change (%)
0       1                 232
1       2                  84
2       3                  82
3       4                  56
4       5                  41
5       6                  40
6       7                  40
7       8                  37
8       9                  28
9      10                  10
10     11                   6
11     12                   6
12     13                  -5
13     14                 -11
14     15                 -16
15     16                 -17
16     17                 -18
17     18                 -19
18     19                 -27
19     20                 -30
20     21                 -36
21     22                 -36
22     23                 -36
23     24                 -37
24     25                 -38
25     26                 -45
26     27                 -58
27     28                 -60
28     29                 -63
29     30                 -67

In [131]:
from bokeh.charts import Bar, output_file, show
from bokeh.sampledata.autompg import autompg as df
from bokeh.models import Range1d
from bokeh.charts import defaults

sorted_plot = Bar(sorted_df, values='Percent change (%)', color="Blue", title='Percent change (%)', legend=None, ylabel="")
# sorted_plot.set(y_range=Range1d(-100, 100))
sorted_plot.y_range = Range1d(-100, 100)    
sorted_plot.xaxis.visible = False
sorted_plot.background_fill_alpha = 0

sorted_plot.width = 600
sorted_plot.height = 250

output_file("bar2.html")
show(sorted_plot)

INFO:bokeh.core.state:Session output file 'bar2.html' already exists, will be overwritten.

In [115]:
from bokeh.models import Range1d

fig = make_fig()
left, right, bottom, top = 3, 9, 4, 10
fig.set(x_range=Range1d(left, right), y_range=Range1d(bottom, top))
show(fig)

range(-100, 100)

In [116]:
for i in range(-3, 3):
    print(i)

-3
-2
-1
0
1
2

In [144]:
processed_df = study.processed_df[['Patient ID', 'Number of solid tumor', 'Number of lymph node', 'Lesion size at the baseline (mm)','Percent change (%)']]
processed_df

,Patient ID,Number of solid tumor,Number of lymph node,Lesion size at the baseline (mm),Percent change (%)
0,1,2,1,NaN,82
1,2,1,2,NaN,6
2,3,1,2,NaN,-38
3,4,3,2,NaN,41
4,5,2,1,NaN,37
5,6,3,2,NaN,-67
6,7,2,1,NaN,-30
7,8,0,2,NaN,-36
8,9,2,0,NaN,232
9,10,3,1,NaN,-36
10,11,1,2,NaN,-16
11,12,1,2,NaN,-27
12,13,2,2,NaN,-60
13,14,1,2,NaN,-18
14,15,3,1,NaN,10
15,16,1,2,NaN,-5
16,17,1,2,NaN,-36
17,18,2,2,NaN,-11
18,19,1,2,NaN,6
19,20,2,1,NaN,-19
20,21,1,2,NaN,-37
21,22,2,2,NaN,28
22,23,2,2,NaN,-63
23,24,2,2,NaN,-45
24,25,4,1,NaN,56
25,26,1,2,NaN,40
26,27,2,2,NaN,40
27,28,2,2,NaN,-17
28,29,0,1,45.0,84
29,30,1,2,NaN,-58

In [145]:
processed_df = study.processed_df[['Patient ID', 'Number of solid tumor', 'Number of lymph node', 'Lesion size at the baseline (mm)','Percent change (%)']]
processed_df.columns = ['ID','NS','NL','LS','PC']
processed_df
# processed_df

    ID  NS  NL    LS   PC
0    1   2   1   NaN   82
1    2   1   2   NaN    6
2    3   1   2   NaN  -38
3    4   3   2   NaN   41
4    5   2   1   NaN   37
5    6   3   2   NaN  -67
6    7   2   1   NaN  -30
7    8   0   2   NaN  -36
8    9   2   0   NaN  232
9   10   3   1   NaN  -36
10  11   1   2   NaN  -16
11  12   1   2   NaN  -27
12  13   2   2   NaN  -60
13  14   1   2   NaN  -18
14  15   3   1   NaN   10
15  16   1   2   NaN   -5
16  17   1   2   NaN  -36
17  18   2   2   NaN  -11
18  19   1   2   NaN    6
19  20   2   1   NaN  -19
20  21   1   2   NaN  -37
21  22   2   2   NaN   28
22  23   2   2   NaN  -63
23  24   2   2   NaN  -45
24  25   4   1   NaN   56
25  26   1   2   NaN   40
26  27   2   2   NaN   40
27  28   2   2   NaN  -17
28  29   0   1  45.0   84
29  30   1   2   NaN  -58

In [ ]:
# @ https://goo.gl/rZo66q

dft = df.T

# 첫번째 컬럼 이름을 data로 변경
dft.rename(columns={'주요재무정보':'date'}, inplace=True)

In [ ]:
- 완료: ID, old_status, LS, PC, new_PR=0, new_PRO=0 새로 생성하기 
- 완료: 기존 df -> LS 의 NaN = 0 치환 후, NS+NL+LS 합쳐서 string 생성 후 새로운 pd의 old_status 로 넣기
- 완료: PS 100 이상 시 100으로 정정해주기 

- 아래 줄은 Intra, inter 따라 view 나눠서 진행 & Intra/Inter 각각 따로 view 함수에 Pro/single, Pro/multi, PR/single, PR/multi 4장씩 df 생성 
- 완료 : PR, PS 각각 따로 아래 줄을 진행, 매칭값 찾아서 새로운 df 의 new_PR, new_Pro 에 매겨주기  

- 완료 : LS != NULL 혹은 != 0 일 경우, "0145" & "84" 로 "single sheet 검색", == null 혹은 == 0 일 경우 "22" & "-45" 로 "multiple sheet 검색"
- 완료 : 엑셀 받아서 새로운 df 들 만들고, 칼럼, 열 매칭하여 값 찾아 새로 생성한 df 에 매기기

In [278]:
import os 
from django.conf import settings

# 뷰에서 스태틱파일 연결하기 : https://goo.gl/GvaE9l
# @ views.py
# url = os.path.join(settings.STATIC_URL, 'calcmain/excel_files/Intra_PR_Multiple.xlsx')

# @ jupyter 
# url = "calcmain" + os.path.join(settings.STATIC_URL, 'calcmain/excel_files/Intra_PR_Multiple.xlsx')

# url
# PR_Multiple.iloc[60:70,]

# for Intra (same radiologist) -> Inter는 다른 것으로 경로 바꿔줘야 함
PR_Multiple = pd.read_excel("calcmain" + os.path.join(settings.STATIC_URL, 'calcmain/excel_files/Intra_PR_Multiple.xlsx'), sheetname=0)
PR_Singular = pd.read_excel("calcmain" + os.path.join(settings.STATIC_URL, 'calcmain/excel_files/Intra_PR_Singular.xlsx'), sheetname=0)
Pro_Multiple = pd.read_excel("calcmain" + os.path.join(settings.STATIC_URL, 'calcmain/excel_files/Intra_Pro_Multiple.xlsx'), sheetname=0)
Pro_Singular = pd.read_excel("calcmain" + os.path.join(settings.STATIC_URL, 'calcmain/excel_files/Intra_Pro_Singular.xlsx'), sheetname=0)
PR_Multiple.head()

   PercentChange   20   30   40   50   02   11   21   12   31   22   41   32
0          -99.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
1          -98.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
2          -97.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
3          -96.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
4          -95.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0

In [279]:
import math
import numpy as np

def change_index(pd_input):
    pd_input.loc[:,'PercentChange'] = np.round(pd_input.loc[:,'PercentChange'])
    pd_input.loc[:,'PercentChange'] = pd_input.loc[:,'PercentChange'].astype(int)
    pd_input = pd_input.set_index(['PercentChange'])
    return pd_input
PR_Multiple = change_index(PR_Multiple)
PR_Singular = change_index(PR_Singular)
Pro_Multiple = change_index(Pro_Multiple)
Pro_Singular = change_index(Pro_Singular)

PR_Multiple.head()

                20   30   40   50   02   11   21   12   31   22   41   32
PercentChange
-99            1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
-98            1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
-97            1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
-96            1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
-95            1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0

In [169]:
# -37 : 	0.97	0.99	1	1	0.96	0.96	1	0.98	1	1	1	1
PR_Multiple.loc[-37,:]    # PR_Multiple.loc[-40,'02'] == 0.98999999999999999

20    0.97
30    0.99
40    1.00
50    1.00
02    0.96
11    0.96
21    1.00
12    0.98
31    1.00
22    1.00
41    1.00
32    1.00
Name: -37, dtype: float64

In [64]:
from django.shortcuts import render, redirect, get_object_or_404
import pandas as pd

study = get_object_or_404(StudyAnalysis, pk=1)
processed_df = study.processed_df[['Patient ID', 'Number of solid tumor', 'Number of lymph node', 'Lesion size at the baseline (mm)','Percent change (%)']]
processed_df.columns = ['ID','NS','NL','LS','PC']

processed_df.loc[:,'NS'] = processed_df.loc[:,'NS'].astype(str)
processed_df.loc[:,'NL'] = processed_df.loc[:,'NL'].astype(str)
processed_df.loc[:,'LS'] = processed_df.loc[:,'LS'].astype(str)

# Setting the serial number to each record
for record in range(len(processed_df.index)):
    if processed_df.loc[record,'LS'] != 'nan': 
        processed_df.loc[record,'old_status'] = processed_df.loc[record,'NS'] + processed_df.loc[record,'NL'] + str(int(float(processed_df.loc[record,'LS'])))
    else:
        processed_df.loc[record,'old_status'] = processed_df.loc[record,'NS'] + processed_df.loc[record,'NL'] 

# Making percent change exceeding 100 to 100
for record in range(len(processed_df.index)):
    if processed_df.loc[record,'PC'] > 100:
        processed_df.loc[record,'PC'] = 100

processed_df = processed_df.drop(processed_df.columns[[1, 2]], axis=1)
processed_df.loc[:,'new_PR'] = processed_df.loc[:,'new_PRO'] = 0
        
processed_df

C:\Anaconda3\lib\site-packages\pandas\core\indexing.py:465: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

C:\Anaconda3\lib\site-packages\pandas\core\indexing.py:288: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[key] = _infer_fill_value(value)

    ID    LS   PC old_status  new_PR  new_PRO
0    1   nan   82         21       0        0
1    2   nan    6         12       0        0
2    3   nan  -38         12       0        0
3    4   nan   41         32       0        0
4    5   nan   37         21       0        0
5    6   nan  -67         32       0        0
6    7   nan  -30         21       0        0
7    8   nan  -36         02       0        0
8    9   nan  100         20       0        0
9   10   nan  -36         31       0        0
10  11   nan  -16         12       0        0
11  12   nan  -27         12       0        0
12  13   nan  -60         22       0        0
13  14   nan  -18         12       0        0
14  15   nan   10         31       0        0
15  16   nan   -5         12       0        0
16  17   nan  -36         12       0        0
17  18   nan  -11         22       0        0
18  19   nan    6         12       0        0
19  20   nan  -19         21       0        0
20  21   nan  -37         12       0        0
21  22   nan   28         22       0        0
22  23   nan  -63         22       0        0
23  24   nan  -45         22       0        0
24  25   nan   56         41       0        0
25  26   nan   40         12       0        0
26  27   nan   40         22       0        0
27  28   nan  -17         22       0        0
28  29  45.0   84       0145       0        0
29  30   nan  -58         12       0        0

In [281]:
# PR_Multiple.head()
# PR_Multiple.loc[82,"21"] # 0.0

# processed_df.loc[0,'PC']
# type(processed_df.loc[0,'PC']) # 82, numpy.int64
# processed_df.loc[0,'old_status']
# type(processed_df.loc[0,'old_status']) # '21', string

# PR_Singular.loc[processed_df.loc[29,'PC'], processed_df.loc[29,'old_status']] # 0.0
# processed_df.loc[29,'PC']
# processed_df.loc[29,'old_status']
# PR_Singular.loc[-58,12]
# PR_Singular.loc[-99,1010] # ok
# Pro_Singular.head(60)
# PR_Singular.head()

# processed_df.loc[28,'LS'] != 'nan'
# processed_df.head()

In [283]:
for record in range(len(processed_df.index)):
    if processed_df.loc[record,'LS'] == 'nan': # multiple 
        processed_df.loc[record,'new_PR'] = PR_Multiple.loc[processed_df.loc[record,'PC'], processed_df.loc[record,'old_status']]
        processed_df.loc[record,'new_PRO'] = Pro_Multiple.loc[processed_df.loc[record,'PC'], processed_df.loc[record,'old_status']]
    else: # singular 
        processed_df.loc[record,'new_PR'] = PR_Singular.loc[processed_df.loc[record,'PC'], processed_df.loc[record,'old_status']]
        processed_df.loc[record,'new_PRO'] = Pro_Singular.loc[processed_df.loc[record,'PC'], processed_df.loc[record,'old_status']]
        
processed_df.head()

   ID   LS  PC old_status  new_PR  new_PRO
0   1  nan  82         21     0.0      1.0
1   2  nan   6         12     0.0      0.0
2   3  nan -38         12     1.0      0.0
3   4  nan  41         32     0.0      1.0
4   5  nan  37         21     0.0      1.0

In [295]:
#     study = get_object_or_404(StudyAnalysis, pk=pk)

# 1-1) Load probability excel files
# for Intra (same radiologist) -> Inter는 다른 것으로 경로 바꿔줘야 함
PR_Multiple = pd.read_excel("calcmain" + os.path.join(settings.STATIC_URL, 'calcmain/excel_files/Intra_PR_Multiple.xlsx'), sheetname=0)
PR_Singular = pd.read_excel("calcmain" + os.path.join(settings.STATIC_URL, 'calcmain/excel_files/Intra_PR_Singular.xlsx'), sheetname=0)
Pro_Multiple = pd.read_excel("calcmain" + os.path.join(settings.STATIC_URL, 'calcmain/excel_files/Intra_Pro_Multiple.xlsx'), sheetname=0)
Pro_Singular = pd.read_excel("calcmain" + os.path.join(settings.STATIC_URL, 'calcmain/excel_files/Intra_Pro_Singular.xlsx'), sheetname=0)

# 1-2) Change the index of probability dataframe
def change_index(pd_input):
    pd_input.loc[:, 'PercentChange'] = np.round(pd_input.loc[:, 'PercentChange'])
    pd_input.loc[:, 'PercentChange'] = pd_input.loc[:, 'PercentChange'].astype(int)
    pd_input = pd_input.set_index(['PercentChange'])
    return pd_input
PR_Multiple = change_index(PR_Multiple)
PR_Singular = change_index(PR_Singular)
Pro_Multiple = change_index(Pro_Multiple)
Pro_Singular = change_index(Pro_Singular)

# 2-1) Prepare the new dataframe about reassessment result (PartialResponse, Progression)
processed_df = study.processed_df[['Patient ID', 'Number of solid tumor', 'Number of lymph node', 'Lesion size at the baseline (mm)', 'Percent change (%)']]
processed_df.columns = ['ID', 'NS', 'NL', 'LS', 'PC']

processed_df.loc[:, 'NS'] = processed_df.loc[:, 'NS'].astype(str)
processed_df.loc[:, 'NL'] = processed_df.loc[:, 'NL'].astype(str)
processed_df.loc[:, 'LS'] = processed_df.loc[:, 'LS'].astype(str)

# 2-2) Setting the serial number to each record
for record in range(len(processed_df.index)):
    if processed_df.loc[record, 'LS'] != 'nan':
        processed_df.loc[record, 'old_status'] = processed_df.loc[record, 'NS'] + processed_df.loc[record, 'NL'] + str(int(float(processed_df.loc[record, 'LS'])))
    else:
        processed_df.loc[record, 'old_status'] = processed_df.loc[record, 'NS'] + processed_df.loc[record, 'NL']

# 2-3) Making [percent change] exceeding 100 to 100
for record in range(len(processed_df.index)):
    if processed_df.loc[record, 'PC'] > 100:
        processed_df.loc[record, 'PC'] = 100

# 2-4) Delete [# of Solid tumor & Lymph node] columns and make new columns
processed_df = processed_df.drop(processed_df.columns[[1, 2]], axis=1)
processed_df.loc[:, 'new_PR'] = processed_df.loc[:, 'new_PRO'] = 0

# 3) Match the records' serial numbers to the probability-df's data
for record in range(len(processed_df.index)):
    if processed_df.loc[record, 'LS'] == 'nan':  # multiple
        processed_df.loc[record, 'new_PR'] = PR_Multiple.loc[processed_df.loc[record, 'PC'], processed_df.loc[record, 'old_status']]
        processed_df.loc[record, 'new_PRO'] = Pro_Multiple.loc[processed_df.loc[record, 'PC'], processed_df.loc[record, 'old_status']]
    else:  # singular
        processed_df.loc[record, 'new_PR'] = PR_Singular.loc[processed_df.loc[record, 'PC'], processed_df.loc[record, 'old_status']]
        processed_df.loc[record, 'new_PRO'] = Pro_Singular.loc[processed_df.loc[record, 'PC'], processed_df.loc[record, 'old_status']]
        
processed_df

FileNotFoundError: [Errno 2] No such file or directory: 'calcmain/static/calcmain/excel_files/Intra_PR_Multiple.xlsx'

In [294]:
from bokeh.charts import Bar, output_file, show
from bokeh.sampledata.autompg import autompg as df
from bokeh.models import Range1d
from bokeh.charts import defaults


# 5) Draw a plot for visualizing patients' diagnosis results.
new_data = {'Index': [i + 1 for i in range(len(processed_df.index))],
           'Probability of PR (%)': sorted(processed_df.loc[:, "new_PR"], reverse=False)}
sorted_df = pd.DataFrame(new_data)

sorted_plot = Bar(sorted_df, values='Probability of PR (%)', color="Blue", title='', legend=None, ylabel="")
sorted_plot.y_range = Range1d(0, 1)
# sorted_plot.xaxis.visible = False
sorted_plot.title.text_font = "Roboto Slab"
sorted_plot.background_fill_alpha = 0
# sorted_plot.border_fill_color = None
sorted_plot.width = 600    # default : 600
sorted_plot.height = 250    # default : 600

output_file("bar2.html")
show(sorted_plot)

# script, div = components(sorted_plot)

INFO:bokeh.core.state:Session output file 'bar2.html' already exists, will be overwritten.

In [303]:
# 여기서부터 final result 시작 
# 넘어온 reassessed_df 의 Assumption 은 해당 id 값에 대하여 선택한 셀렉트박스 Assumption 값을 따름

from django.shortcuts import render, redirect, get_object_or_404
import pandas as pd


study = get_object_or_404(StudyAnalysis, pk=24)
# input_df = study.processed_df

# study.up_patients

input_df = study.reassessed_df
input_df


# len(input_df.index) # 30
# base_index = len(input_df.index) 
# base_index # 30

    ID    LS  PC old_status  new_PR  new_PRO
0    1   nan  10         21    0.00     0.00
1    2   nan   6         12    0.00     0.00
2    3   nan   0         12    0.00     0.00
3    4   nan  -4         32    0.00     0.00
4    5   nan  -7         21    0.00     0.00
5    6   nan -14         32    0.00     0.00
6    7   nan -17         21    0.00     0.00
7    8   nan -32         02    0.69     0.00
8    9   nan -17         20    0.00     0.00
9   10   nan -36         31    0.99     0.00
10  11   nan -16         12    0.00     0.00
11  12   nan -27         12    0.18     0.00
12  13   nan -60         22    1.00     0.00
13  14   nan -18         12    0.00     0.00
14  15   nan   0         31    0.00     0.00
15  16   nan  17         12    0.00     0.27
16  17   nan  24         12    0.00     0.80
17  18   nan  44         22    0.00     1.00
18  19   nan   6         12    0.00     0.00
19  20   nan -19         21    0.00     0.00
20  21   nan -37         12    0.98     0.00
21  22   nan  28         22    0.00     0.98
22  23   nan -63         22    1.00     0.00
23  24   nan -45         22    1.00     0.00
24  25   nan  56         41    0.00     1.00
25  26   nan  40         12    0.00     1.00
26  27   nan  40         22    0.00     1.00
27  28   nan -17         22    0.00     0.00
28  29  45.0  84       0145    0.00     1.00
29  30   nan -58         12    1.00     0.00

In [304]:
# Add rows of UP patients 

# study.up_patients # 20
base_index = len(input_df.index) # 30
for i in range(study.up_patients):
    input_df.loc[base_index + i, "new_PR"] = 0
    input_df.loc[base_index + i, "new_PRO"] = 1
    
input_df

      ID    LS    PC old_status  new_PR  new_PRO
0    1.0   nan  10.0         21    0.00     0.00
1    2.0   nan   6.0         12    0.00     0.00
2    3.0   nan   0.0         12    0.00     0.00
3    4.0   nan  -4.0         32    0.00     0.00
4    5.0   nan  -7.0         21    0.00     0.00
5    6.0   nan -14.0         32    0.00     0.00
6    7.0   nan -17.0         21    0.00     0.00
7    8.0   nan -32.0         02    0.69     0.00
8    9.0   nan -17.0         20    0.00     0.00
9   10.0   nan -36.0         31    0.99     0.00
10  11.0   nan -16.0         12    0.00     0.00
11  12.0   nan -27.0         12    0.18     0.00
12  13.0   nan -60.0         22    1.00     0.00
13  14.0   nan -18.0         12    0.00     0.00
14  15.0   nan   0.0         31    0.00     0.00
15  16.0   nan  17.0         12    0.00     0.27
16  17.0   nan  24.0         12    0.00     0.80
17  18.0   nan  44.0         22    0.00     1.00
18  19.0   nan   6.0         12    0.00     0.00
19  20.0   nan -19.0         21    0.00     0.00
20  21.0   nan -37.0         12    0.98     0.00
21  22.0   nan  28.0         22    0.00     0.98
22  23.0   nan -63.0         22    1.00     0.00
23  24.0   nan -45.0         22    1.00     0.00
24  25.0   nan  56.0         41    0.00     1.00
25  26.0   nan  40.0         12    0.00     1.00
26  27.0   nan  40.0         22    0.00     1.00
27  28.0   nan -17.0         22    0.00     0.00
28  29.0  45.0  84.0       0145    0.00     1.00
29  30.0   nan -58.0         12    1.00     0.00
30   NaN   NaN   NaN        NaN    0.00     1.00
31   NaN   NaN   NaN        NaN    0.00     1.00
32   NaN   NaN   NaN        NaN    0.00     1.00
33   NaN   NaN   NaN        NaN    0.00     1.00
34   NaN   NaN   NaN        NaN    0.00     1.00

In [34]:
# 0~49 printed
# for record in range(len(input_df.index)):
#     print(record)

# index 16	ID 17.0	nan	Percent_Change = 24.0	12	0.00	new_PRO = 0.64
# input_df.loc[16, 'new_PRO'] # 0.64000000000000001
bernoulli.rvs(input_df.loc[16, 'new_PRO'], size=10)

array([0, 0, 1, 0, 0, 0, 0, 1, 0, 1])

In [262]:
# [np.random.binomial(1,p=0.7) for i in range(10)]
# bernoulli.rvs(0.7, size=10)



#     bernoulli_dict_PR[record] = bernoulli.rvs(input_df.loc[record, 'new_PR'], size=1000)
#     bernoulli_dict_PR0[record] = bernoulli.rvs(input_df.loc[record, 'new_PRO'], size=1000)

# [np.random.binomial(1,p=input_df.loc[record, 'new_PR']) for i in range(1000)]
# [np.random.binomial(1,p=input_df.loc[record, 'new_PRO']) for i in range(1000)]


# np.random.choice([0, 1], size=(10,), p=0.7)
np.random.choice([0, 1], size=(10,), p=[1-input_df.loc[16, 'new_PRO'], input_df.loc[16, 'new_PRO']])

array([0, 0, 1, 1, 1, 1, 1, 0, 1, 1])

In [321]:
from scipy.stats import bernoulli

# Key = Patient ID, Value = Bernoulli random variable
bernoulli_dict_PR = {}
bernoulli_dict_PR0 = {}

# Column = Key = Patients' ID, Row = Value = 1000 Bernoulli random variables derived from patients new_PR or new_PRO proportion
for record in range(len(input_df.index)):
#     bernoulli_dict_PR[record] = [np.random.binomial(1,p=input_df.loc[record, 'new_PR']) for i in range(1000)]
#     bernoulli_dict_PR0[record] = [np.random.binomial(1,p=input_df.loc[record, 'new_PRO']) for i in range(1000)]
#     bernoulli_dict_PR[record] = bernoulli.rvs(input_df.loc[record, 'new_PR'], size=1000)
#     bernoulli_dict_PR0[record] = bernoulli.rvs(input_df.loc[record, 'new_PRO'], size=1000)
    bernoulli_dict_PR[record] = np.random.choice([0, 1], size=(1000,), p=[1-input_df.loc[record, 'new_PR'], input_df.loc[record, 'new_PR']])
    bernoulli_dict_PR0[record] = np.random.choice([0, 1], size=(1000,), p=[1-input_df.loc[record, 'new_PRO'], input_df.loc[record, 'new_PRO']])
    
PR_df = pd.DataFrame(bernoulli_dict_PR)
PR_df.loc[:, "NewProb(PR)"] = PR_df.sum(axis=1)/len(PR_df.columns) # axis : 1 = row-oriented sum
PRO_df = pd.DataFrame(bernoulli_dict_PR0)
PRO_df.loc[:, "NewProb(PRO)"] = PRO_df.sum(axis=1)/len(PRO_df.columns) # axis : 1 = row-oriented sum

PR_df.head()
# PRO_df.loc[200,'NewProb(PRO)']

,0,1,2,3,4,5,6,7,8,9,...,26,27,28,29,30,31,32,33,34,NewProb(PR)
0,0,0,0,0,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,0,0.2
1,0,0,0,0,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,0,0.2
2,0,0,0,0,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,0,0.2
3,0,0,0,0,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,0,0.2
4,0,0,0,0,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,0,0.2

In [202]:
# DF 만들기 전에 *100 및 INT 적용하지 않을 경우 (개발 상에 반영된 것은 다음 셀)

import numpy as np 

new_data = {'Index': [i + 1 for i in range(len(PR_df.index))],
           'Probability of PR (%)': sorted(PR_df.loc[:, "NewProb(PR)"], reverse=False)}
sorted_PR_df = pd.DataFrame(new_data)

quantile_bottom_pr = int(sorted_PR_df.loc[25, "Probability of PR (%)"] * 100) # 26th
quantile_top_pr = int(sorted_PR_df.loc[974, "Probability of PR (%)"] * 100) # 975th
quantile_median_pr = int((sorted_PR_df.loc[499, "Probability of PR (%)"] + sorted_PR_df.loc[500, "Probability of PR (%)"]) / 2 * 100)

new_data = {'Index': [i + 1 for i in range(len(PRO_df.index))],
           'Probability of PRO (%)': sorted(PRO_df.loc[:, "NewProb(PRO)"], reverse=False)}
sorted_PRO_df = pd.DataFrame(new_data)

quantile_bottom_pro = int(sorted_PRO_df.loc[25, "Probability of PRO (%)"] * 100) # 26th
quantile_top_pro = int(sorted_PRO_df.loc[974, "Probability of PRO (%)"] * 100) # 975th
quantile_median_pro = int((sorted_PRO_df.loc[499, "Probability of PRO (%)"] + sorted_PRO_df.loc[500, "Probability of PRO (%)"]) / 2 * 100)

sorted_PR_df.head()

   Index  Probability of PR (%)
0      1                   0.08
1      2                   0.08
2      3                   0.08
3      4                   0.08
4      5                   0.08

In [320]:
import numpy as np 

new_data = {'Index': [i + 1 for i in range(len(PR_df.index))],
           'Probability of PR (%)': sorted((PR_df.loc[:, "NewProb(PR)"] * 100).astype(int), reverse=False)}
sorted_PR_df = pd.DataFrame(new_data)

quantile_bottom_pr = sorted_PR_df.loc[25, "Probability of PR (%)"] # 26th
quantile_top_pr = sorted_PR_df.loc[974, "Probability of PR (%)"] # 975th
quantile_median_pr = int((sorted_PR_df.loc[499, "Probability of PR (%)"] + sorted_PR_df.loc[500, "Probability of PR (%)"]) / 2)

new_data = {'Index': [i + 1 for i in range(len(PRO_df.index))],
           'Probability of PRO (%)': sorted((PRO_df.loc[:, "NewProb(PRO)"] * 100).astype(int), reverse=False)}
sorted_PRO_df = pd.DataFrame(new_data)

quantile_bottom_pro = sorted_PRO_df.loc[25, "Probability of PRO (%)"] # 26th
quantile_top_pro = sorted_PRO_df.loc[974, "Probability of PRO (%)"] # 975th
quantile_median_pro = int((sorted_PRO_df.loc[499, "Probability of PRO (%)"] + sorted_PRO_df.loc[500, "Probability of PRO (%)"]) / 2)
sorted_PR_df.head()

# sorted(PR_df.loc[:,'NewProb(PR)'], reverse=False)
# sorted_PR_df.loc[:,"Probability of PR (%)"]

   Index  Probability of PR (%)
0      1                     14
1      2                     14
2      3                     14
3      4                     14
4      5                     14

In [318]:
print(quantile_bottom_pr, quantile_median_pr, quantile_top_pr)
print(quantile_bottom_pro, quantile_median_pro, quantile_top_pro)

17 20 22
31 34 37

In [319]:
from bokeh.charts import Bar, Histogram, output_file, show
from bokeh.sampledata.autompg import autompg as df
from bokeh.models import Range1d
from bokeh.charts import defaults


# 5) Draw a plot for visualizing patients' diagnosis results.

pr_plot = Histogram(sorted_PR_df, values='Probability of PR (%)', bins=15, color='blue', title='', ylabel='', xlabel='')
pr_plot.title.text_font = "Roboto Slab"
# pr_plot.background_fill_alpha = 0
# pr_plot.border_fill_color = None
pr_plot.width = 600    # default : 600
pr_plot.height = 250    # default : 600

output_file("histogram2.html",)

show(pr_plot)

# script, div = components(sorted_plot)

INFO:bokeh.core.state:Session output file 'histogram2.html' already exists, will be overwritten.

In [38]:
bernoulli_dict = {}

# range 값 = 환자 수 
# for i in range(5):
#     bernoulli_dict[i] = None


# 칼럼 = 환자 ID, 열 = 환자ID의 베르누이 분포로부터의 변수 
for i in range(5):
    bernoulli_dict[i] = bernoulli.rvs(0.77, size=15) # 0.77 -> 해당 칼럼 ID 의 환자의 row 상의 PR/PRO 확률값이 들어와야 함 
    
df = pd.DataFrame(bernoulli_dict)
df.loc[:, "Sum"] = df.sum(axis=1)/len(df.columns) # df 가 아닌 환자 수 = column 수가 되어야 함
df

# for i in range(len(df.index)):
#     df.loc[i, "Sum"] = pd.sum(axis=0)

    0  1  2  3  4  Sum
0   1  1  0  0  1  0.6
1   0  1  0  1  1  0.6
2   1  1  0  1  1  0.8
3   1  0  1  0  1  0.6
4   1  1  0  1  1  0.8
5   1  1  1  1  1  1.0
6   1  1  1  1  1  1.0
7   0  0  1  0  1  0.4
8   0  1  1  1  1  0.8
9   1  0  1  1  1  0.8
10  1  1  1  0  1  0.8
11  1  1  1  1  0  0.8
12  1  0  1  1  0  0.6
13  1  1  1  1  1  1.0
14  1  0  1  1  1  0.8

In [325]:

from django.shortcuts import render, redirect, get_object_or_404
import pandas as pd
import re
import math


study = get_object_or_404(StudyAnalysis, pk=28)


main_df = pd.read_excel(study.imported_sheet, sheetname=0)

# Change column names and change uppercase characters(organ) into lowercase
main_df.columns = ['ID', 'Organ', 'Lesion size at baseline (mm)', 'Lesion size at post-treatment (mm)']
main_df["Organ"] = main_df["Organ"].str.lower()

# Generate a dataframe for processing the data
process_df = pd.DataFrame({'Patient ID': list(set([int(i) for i in main_df.ID]))})
process_df["Number of solid tumor"] = 0
process_df["Number of lymph node"] = 0
process_df["sum_base"] = 0
process_df["sum_post"] = 0
process_df["Lesion size at the baseline (mm)"] = np.nan
process_df["Percent change (%)"] = 0

# Check records and update cells
for record in range(len(main_df.index)):
    record_id = main_df.iloc[:, 0][record]
    lesion_name = main_df.iloc[:, 1][record]
    input_id = record_id - 1

    if re.match("lymph*", lesion_name):
        process_df["Number of lymph node"][input_id] += 1
    else:
        process_df["Number of solid tumor"][input_id] += 1
    process_df["sum_base"][input_id] += main_df.iloc[:, 2][record]
    process_df["sum_post"][input_id] += main_df.iloc[:, 3][record]

# Check processed dataframe and update cells
for record in range(len(process_df.index)):
    process_df['Percent change (%)'][record] = math.floor((process_df["sum_post"][record] - process_df["sum_base"][record]) / process_df["sum_base"][record] * 100)
    if process_df["Number of lymph node"][record] + process_df["Number of solid tumor"][record] == 1:
        process_df["Lesion size at the baseline (mm)"][record] = int(main_df.loc[main_df['ID'] == record + 1]['Lesion size at baseline (mm)'])
    
process_df

C:\Anaconda3\lib\site-packages\ipykernel\__main__.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

WARNING:py.warnings:C:\Anaconda3\lib\site-packages\ipykernel\__main__.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Anaconda3\lib\site-packages\ipykernel\__main__.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

WARNING:py.warnings:C:\Anaconda3\lib\site-packages\ipykernel\__main__.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Anaconda3\lib\site-packages\ipykernel\__main__.py:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

WARNING:py.warnings:C:\Anaconda3\lib\site-packages\ipykernel\__main__.py:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Anaconda3\lib\site-packages\ipykernel\__main__.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

WARNING:py.warnings:C:\Anaconda3\lib\site-packages\ipykernel\__main__.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Anaconda3\lib\site-packages\ipykernel\__main__.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

WARNING:py.warnings:C:\Anaconda3\lib\site-packages\ipykernel\__main__.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Anaconda3\lib\site-packages\ipykernel\__main__.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

WARNING:py.warnings:C:\Anaconda3\lib\site-packages\ipykernel\__main__.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,Patient ID,Number of solid tumor,Number of lymph node,sum_base,sum_post,Lesion size at the baseline (mm),Percent change (%)
0,1,2,1,140,155,NaN,10
1,2,1,2,144,154,NaN,6
2,3,1,2,148,149,NaN,0
3,4,3,2,332,320,NaN,-4
4,5,2,1,161,150,NaN,-7
5,6,3,2,388,335,NaN,-14
6,7,2,1,233,195,NaN,-17
7,8,0,2,138,95,NaN,-32
8,9,2,0,62,52,NaN,-17
9,10,3,1,373,239,NaN,-36
10,11,1,2,188,159,NaN,-16
11,12,1,2,139,102,NaN,-27
12,13,2,2,264,108,NaN,-60
13,14,1,2,218,179,NaN,-18
14,15,3,1,278,280,NaN,0
15,16,1,2,126,148,NaN,17
16,17,1,2,254,315,NaN,24
17,18,2,2,233,336,NaN,44
18,19,1,2,191,204,NaN,6
19,20,2,1,317,258,NaN,-19
20,21,1,2,237,151,NaN,-37
21,22,2,2,103,132,NaN,28
22,23,2,2,375,142,NaN,-63
23,24,2,2,256,142,NaN,-45
24,25,4,1,307,480,NaN,56
25,26,1,2,90,126,NaN,40
26,27,2,2,224,315,NaN,40
27,28,2,2,311,259,NaN,-17
28,29,0,1,45,83,45.0,84
29,30,1,2,199,84,NaN,-58

In [6]:

from django.shortcuts import render, redirect, get_object_or_404
import pandas as pd
import numpy as np
import re
import math


study = get_object_or_404(StudyAnalysis, pk=28)
main_df = pd.read_excel(study.imported_sheet, sheetname=0)

# Change column names and change uppercase characters(organ) into lowercase
main_df.columns = ['ID', 'Organ', 'Lesion size at baseline (mm)', 'Lesion size at post-treatment (mm)']
main_df["Organ"] = main_df["Organ"].str.lower()

# Generate a dataframe for processing the data
process_df = pd.DataFrame({'Patient ID': list(set([int(i) for i in main_df.ID]))})
process_df.loc[:,"Number of solid tumor"] = 0
process_df.loc[:,"Number of lymph node"] = 0
process_df.loc[:,"sum_base"] = 0
process_df.loc[:,"sum_post"] = 0
process_df.loc[:,"Lesion size at the baseline (mm)"] = np.nan
process_df.loc[:,"Percent change (%)"] = 0

# Check records and update cells
for record in range(len(main_df.index)):
    record_id = main_df.iloc[:, 0][record]
    lesion_name = main_df.iloc[:, 1][record]
    input_id = record_id - 1

    if re.match("lymph*", lesion_name):
        process_df.loc[input_id,"Number of lymph node"] += 1
    else:
        process_df.loc[input_id,"Number of solid tumor"] += 1
    process_df.loc[input_id,"sum_base"] += main_df.iloc[:, 2][record]
    process_df.loc[input_id,"sum_post"] += main_df.iloc[:, 3][record]


process_df.loc[:,"Number of solid tumor"] = process_df.loc[:,"Number of solid tumor"].astype(int)
process_df.loc[:,"Number of lymph node"] = process_df.loc[:,"Number of lymph node"].astype(int)
process_df.loc[:,"sum_base"] = process_df.loc[:,"sum_base"].astype(int)
process_df.loc[:,"sum_post"] = process_df.loc[:,"sum_post"].astype(int)

# Check processed dataframe and update cells
for record in range(len(process_df.index)):
    process_df.loc[record, 'Percent change (%)'] = math.floor((process_df.loc[record, "sum_post"] - process_df.loc[record, "sum_base"]) / process_df.loc[record, "sum_base"] * 100)
    if process_df.loc[record, "Number of lymph node"] + process_df.loc[record, "Number of solid tumor"] == 1:
        process_df.loc[record, "Lesion size at the baseline (mm)"] = int(main_df.loc[main_df['ID'] == record + 1]['Lesion size at baseline (mm)'])
    
process_df

,Patient ID,Number of solid tumor,Number of lymph node,sum_base,sum_post,Lesion size at the baseline (mm),Percent change (%)
0,1,2,1,140,155,NaN,10
1,2,1,2,144,154,NaN,6
2,3,1,2,148,149,NaN,0
3,4,3,2,332,320,NaN,-4
4,5,2,1,161,150,NaN,-7
5,6,3,2,388,335,NaN,-14
6,7,2,1,233,195,NaN,-17
7,8,0,2,138,95,NaN,-32
8,9,2,0,62,52,NaN,-17
9,10,3,1,373,239,NaN,-36
10,11,1,2,188,159,NaN,-16
11,12,1,2,139,102,NaN,-27
12,13,2,2,264,108,NaN,-60
13,14,1,2,218,179,NaN,-18
14,15,3,1,278,280,NaN,0
15,16,1,2,126,148,NaN,17
16,17,1,2,254,315,NaN,24
17,18,2,2,233,336,NaN,44
18,19,1,2,191,204,NaN,6
19,20,2,1,317,258,NaN,-19
20,21,1,2,237,151,NaN,-37
21,22,2,2,103,132,NaN,28
22,23,2,2,375,142,NaN,-63
23,24,2,2,256,142,NaN,-45
24,25,4,1,307,480,NaN,56
25,26,1,2,90,126,NaN,40
26,27,2,2,224,315,NaN,40
27,28,2,2,311,259,NaN,-17
28,29,0,1,45,83,45.0,84
29,30,1,2,199,84,NaN,-58