In [4]:
# 수정 작업 20170310

from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
import re
import math
import pandas as pd
import numpy as np
from bokeh.charts import Bar, Histogram  # defaults, output_file, show
from bokeh.models import Range1d
from bokeh.embed import components
import os


study = get_object_or_404(StudyAnalysis, pk=35)
main_df = pd.read_excel(study.imported_sheet, sheetname=0)

# Change column names and change uppercase characters(organ) into lowercase
main_df.columns = ['ID', 'Organ', 'Lesion size at baseline (mm)', 'Lesion size at post-treatment (mm)']
main_df["Organ"] = main_df["Organ"].str.lower()

# Generate a dataframe for processing the data
process_df = pd.DataFrame({'Patient ID': list(set([int(i) for i in main_df.ID]))})
process_df.loc[:,"Number of solid organ tumor"] = 0
process_df.loc[:,"Number of lymph node"] = 0
process_df.loc[:,"Tumor burden at the baseline (mm)"] = 0
process_df.loc[:,"Tumor burden at the post-treatment (mm)"] = 0
process_df.loc[:,"Lesion size at the baseline (mm)"] = np.nan
process_df.loc[:,"Percent change (%)"] = 0

# Check records and update cells
for record in range(len(main_df.index)):
    record_id = main_df.iloc[:, 0][record]
    lesion_name = main_df.iloc[:, 1][record]
    input_id = record_id - 1

    if re.match("lymph*", lesion_name):
        process_df.loc[input_id,"Number of lymph node"] += 1
    else:
        process_df.loc[input_id,"Number of solid organ tumor"] += 1
    process_df.loc[input_id,"Tumor burden at the baseline (mm)"] += main_df.iloc[:, 2][record]
    process_df.loc[input_id,"Tumor burden at the post-treatment (mm)"] += main_df.iloc[:, 3][record]


process_df.loc[:,"Number of solid organ tumor"] = process_df.loc[:,"Number of solid organ tumor"].astype(int)
process_df.loc[:,"Number of lymph node"] = process_df.loc[:,"Number of lymph node"].astype(int)
process_df.loc[:,"Tumor burden at the baseline (mm)"] = process_df.loc[:,"Tumor burden at the baseline (mm)"].astype(int)
process_df.loc[:,"Tumor burden at the post-treatment (mm)"] = process_df.loc[:,"Tumor burden at the post-treatment (mm)"].astype(int)

# Check processed dataframe and update cells
for record in range(len(process_df.index)):
    process_df.loc[record, 'Percent change (%)'] = math.floor((process_df.loc[record, "Tumor burden at the post-treatment (mm)"] - process_df.loc[record, "Tumor burden at the baseline (mm)"]) / process_df.loc[record, "Tumor burden at the baseline (mm)"] * 100)
    if process_df.loc[record, "Number of lymph node"] + process_df.loc[record, "Number of solid organ tumor"] == 1:
        process_df.loc[record, "Lesion size at the baseline (mm)"] = int(main_df.loc[main_df['ID'] == record + 1]['Lesion size at baseline (mm)'])

process_df

,Patient ID,Number of solid organ tumor,Number of lymph node,Tumor burden at the baseline (mm),Tumor burden at the post-treatment (mm),Lesion size at the baseline (mm),Percent change (%)
0,1,2,1,140,155,NaN,10
1,2,1,2,144,154,NaN,6
2,3,1,2,148,149,NaN,0
3,4,3,2,332,320,NaN,-4
4,5,2,1,161,150,NaN,-7
5,6,3,2,388,335,NaN,-14
6,7,2,1,233,195,NaN,-17
7,8,0,2,138,95,NaN,-32
8,9,2,0,62,52,NaN,-17
9,10,3,1,373,239,NaN,-36
10,11,1,2,188,159,NaN,-16
11,12,1,2,139,102,NaN,-27
12,13,2,2,264,108,NaN,-60
13,14,1,2,218,179,NaN,-18
14,15,3,1,278,280,NaN,0
15,16,1,2,126,148,NaN,17
16,17,1,2,254,315,NaN,24
17,18,2,2,233,336,NaN,44
18,19,1,2,191,204,NaN,6
19,20,2,1,317,258,NaN,-19
20,21,1,2,237,151,NaN,-37
21,22,2,2,103,132,NaN,28
22,23,2,2,375,142,NaN,-63
23,24,2,2,256,142,NaN,-45
24,25,4,1,307,480,NaN,56
25,26,1,2,90,126,NaN,40
26,27,2,2,224,315,NaN,40
27,28,2,2,311,259,NaN,-17
28,29,0,1,45,83,45.0,84
29,30,1,2,199,84,NaN,-58